import './globals.css'
import Header from '@/components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en" className='h-screen scroll-smooth'>
      <body className="bg-backgroundColor text-whiteish font-space h-full">
        <div className='fixed w-full bg-backgroundColorTransparent backdrop-blur-sm z-10'>
          <Header />
        </div>
        <>
          {children}
        </>
      </body>
    </html>
  )
}
